"""Add goal notes order recurrence

Revision ID: 0010f5b3b9ef
Revises: 2c990641b5d3
Create Date: 2026-02-28 14:44:18.445294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0010f5b3b9ef'
down_revision = '2c990641b5d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('order', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('recurrence', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('recurrence')
        batch_op.drop_column('order')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
