"""add job_description to interview_applications

Revision ID: 16d92d839af3
Revises: f8d8e997a035
Create Date: 2026-02-27 16:34:26.190158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d92d839af3'
down_revision = 'f8d8e997a035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_applications', schema=None) as batch_op:
        batch_op.drop_column('job_description')

    # ### end Alembic commands ###
