"""Added Gym Tracker models

Revision ID: 180b2dcc143d
Revises: be13383f01a7
Create Date: 2026-02-27 10:12:30.410041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180b2dcc143d'
down_revision = 'be13383f01a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_days',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('water_glasses', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_gym_date')
    )
    op.create_table('gym_exercises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gym_day_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gym_day_id'], ['gym_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gym_meals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gym_day_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gym_day_id'], ['gym_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gym_meals')
    op.drop_table('gym_exercises')
    op.drop_table('gym_days')
    # ### end Alembic commands ###
