"""add source, resume, interviewers to interview_applications

Revision ID: 2571c6dd1a27
Revises: 79c7afe5fd4e
Create Date: 2026-02-27 16:47:20.725187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2571c6dd1a27'
down_revision = '79c7afe5fd4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_source', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('resume_version', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('interviewers', sa.Text(), nullable=True))

    # Populate existing rows with default value
    op.execute("UPDATE interview_applications SET interviewers = '[]'")

    with op.batch_alter_table('interview_applications', schema=None) as batch_op:
        batch_op.alter_column('interviewers', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_applications', schema=None) as batch_op:
        batch_op.drop_column('interviewers')
        batch_op.drop_column('resume_version')
        batch_op.drop_column('application_source')

    # ### end Alembic commands ###
