"""add goal categories colors and deadlines

Revision ID: 2c990641b5d3
Revises: 123e408f9715
Create Date: 2026-02-28 14:07:17.392752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c990641b5d3'
down_revision = '123e408f9715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.String(length=20), nullable=True))

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('is_archived')
        batch_op.drop_column('color')
        batch_op.drop_column('category')

    with op.batch_alter_table('goal_steps', schema=None) as batch_op:
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###
