"""Add priority and due_date to projects

Revision ID: 2de78f936cef
Revises: 1139729d43e9
Create Date: 2026-02-27 13:01:14.940161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de78f936cef'
down_revision = '1139729d43e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
    
    # Set default priority for existing rows
    op.execute("UPDATE projects SET priority = 'medium' WHERE priority IS NULL")
    
    # Now make it non-nullable
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('priority', nullable=False)
        # Update status default for existing data if it's currently 'active' or something else
        # Kanban needs 'backlog', 'in-progress', 'review', 'completed'
    
    op.execute("UPDATE projects SET status = 'backlog' WHERE status NOT IN ('backlog', 'in-progress', 'review', 'completed')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('due_date')
        batch_op.drop_column('priority')
    # ### end Alembic commands ###
