"""Added pushups pullups squads tracking

Revision ID: 2f79a5af2b36
Revises: 180b2dcc143d
Create Date: 2026-02-27 10:19:44.054699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f79a5af2b36'
down_revision = '180b2dcc143d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pushups', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pullups', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('squads', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_days', schema=None) as batch_op:
        batch_op.drop_column('squads')
        batch_op.drop_column('pullups')
        batch_op.drop_column('pushups')

    # ### end Alembic commands ###
