"""add lending transaction model

Revision ID: 36bfeb133ece
Revises: 6ab5fa0d962b
Create Date: 2026-02-26 18:14:22.103910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36bfeb133ece'
down_revision = '6ab5fa0d962b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lending_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lending_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lending_id'], ['lending_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lending_transactions')
    # ### end Alembic commands ###
