"""add_project_activities

Revision ID: 45ba443188e6
Revises: dc6352a28d06
Create Date: 2026-02-27 15:10:00.376960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ba443188e6'
down_revision = 'dc6352a28d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_activities_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_activities_created_at'))

    op.drop_table('project_activities')
    # ### end Alembic commands ###
