"""Add total_spend to credit_cards

Revision ID: 45d25fc873ce
Revises: 36bfeb133ece
Create Date: 2026-02-26 20:39:57.272749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d25fc873ce'
down_revision = '36bfeb133ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_spend', sa.Float(), nullable=False, server_default='0.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.drop_column('total_spend')

    # ### end Alembic commands ###
