"""add completed_at to goal and goalstep

Revision ID: 48fcb94d5207
Revises: c810640a542b
Create Date: 2026-03-01 04:28:55.856610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48fcb94d5207'
down_revision = 'c810640a542b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    with op.batch_alter_table('goal_steps', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
