"""add job_portal fields to interview_applications

Revision ID: 491ed724cfb0
Revises: 16d92d839af3
Create Date: 2026-02-27 16:37:58.229113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491ed724cfb0'
down_revision = '16d92d839af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_portal_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('job_portal_username', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('job_portal_password', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_applications', schema=None) as batch_op:
        batch_op.drop_column('job_portal_password')
        batch_op.drop_column('job_portal_username')
        batch_op.drop_column('job_portal_url')

    # ### end Alembic commands ###
