"""add lending records model

Revision ID: 6ab5fa0d962b
Revises: ceb4736e2da0
Create Date: 2026-02-26 17:40:42.879907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab5fa0d962b'
down_revision = 'ceb4736e2da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lending_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('borrower', sa.String(length=255), nullable=False),
    sa.Column('total_lent', sa.Float(), nullable=False),
    sa.Column('returned', sa.Float(), nullable=False),
    sa.Column('due_date', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lending_records')
    # ### end Alembic commands ###
