"""add daily_routines table

Revision ID: 6eef5f591fda
Revises: a54af398d0fa
Create Date: 2026-02-26 12:31:09.971364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eef5f591fda'
down_revision = 'a54af398d0fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_routines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('entries', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date')
    )
    with op.batch_alter_table('daily_routines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_routines_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_routines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_routines_date'))

    op.drop_table('daily_routines')
    # ### end Alembic commands ###
