"""Add is_pinned to Goal

Revision ID: 701d539abc7e
Revises: b1ebb85de399
Create Date: 2026-02-28 21:03:06.505840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701d539abc7e'
down_revision = 'b1ebb85de399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('is_pinned')

    # ### end Alembic commands ###
