"""add applied_date to interview_applications

Revision ID: 79c7afe5fd4e
Revises: 491ed724cfb0
Create Date: 2026-02-27 16:42:04.802019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c7afe5fd4e'
down_revision = '491ed724cfb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applied_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_applications', schema=None) as batch_op:
        batch_op.drop_column('applied_date')

    # ### end Alembic commands ###
