"""add gym goals

Revision ID: 7a1f948158f3
Revises: d9079f479364
Create Date: 2026-02-27 11:21:02.183110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1f948158f3'
down_revision = 'd9079f479364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_goals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('target_water', sa.Integer(), nullable=False),
    sa.Column('target_protein', sa.Float(), nullable=False),
    sa.Column('target_calories', sa.Integer(), nullable=False),
    sa.Column('target_pushups', sa.Integer(), nullable=False),
    sa.Column('target_pullups', sa.Integer(), nullable=False),
    sa.Column('target_squads', sa.Integer(), nullable=False),
    sa.Column('target_workouts_per_week', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gym_goals')
    # ### end Alembic commands ###
