"""add streaks and dependencies

Revision ID: 843bbd8f3e5d
Revises: 0010f5b3b9ef
Create Date: 2026-02-28 15:33:08.722010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843bbd8f3e5d'
down_revision = '0010f5b3b9ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_dependencies',
    sa.Column('goal_id', sa.String(length=36), nullable=False),
    sa.Column('depends_on_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('goal_id', 'depends_on_id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_streak_date', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('last_streak_date')
        batch_op.drop_column('streak_count')

    op.drop_table('goal_dependencies')
    # ### end Alembic commands ###
