"""Add goal enhancements (image, project_id, is_milestone)

Revision ID: b1ebb85de399
Revises: 843bbd8f3e5d
Create Date: 2026-02-28 20:14:24.279445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ebb85de399'
down_revision = '843bbd8f3e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_milestone', sa.Boolean(), server_default='false', nullable=False))

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('image_url')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('goal_steps', schema=None) as batch_op:
        batch_op.drop_column('is_milestone')

    # ### end Alembic commands ###
