"""Add role and subscription_plan to User

Revision ID: be13383f01a7
Revises: 45d25fc873ce
Create Date: 2026-02-27 09:08:30.947156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be13383f01a7'
down_revision = '45d25fc873ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))
        batch_op.add_column(sa.Column('subscription_plan', sa.String(length=50), nullable=False, server_default='free'))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('subscription_plan')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
