"""add due date to credit cards

Revision ID: ceb4736e2da0
Revises: fa64da6df714
Create Date: 2026-02-26 17:22:54.737005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb4736e2da0'
down_revision = 'fa64da6df714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
