"""professional_tracker_updates

Revision ID: d2c1cefab647
Revises: 2de78f936cef
Create Date: 2026-02-27 13:25:42.396717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c1cefab647'
down_revision = '2de78f936cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pomodoro_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('project_task_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'project_tasks', ['project_task_id'], ['id'])
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('archived')
        batch_op.drop_column('category')

    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.drop_column('due_date')
        batch_op.drop_column('priority')
        batch_op.drop_column('description')

    with op.batch_alter_table('pomodoro_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('project_task_id')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
