"""add muscle group

Revision ID: d9079f479364
Revises: 2f79a5af2b36
Create Date: 2026-02-27 11:18:31.254716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9079f479364'
down_revision = '2f79a5af2b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('muscle_group', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_exercises', schema=None) as batch_op:
        batch_op.drop_column('muscle_group')

    # ### end Alembic commands ###
