"""add interview_applications

Revision ID: f8d8e997a035
Revises: e761c0af9503
Create Date: 2026-02-27 15:58:15.035314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d8e997a035'
down_revision = 'e761c0af9503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('company_phone', sa.String(length=50), nullable=True),
    sa.Column('company_email', sa.String(length=255), nullable=True),
    sa.Column('expected_ctc', sa.String(length=100), nullable=True),
    sa.Column('current_ctc', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('interview_date', sa.DateTime(), nullable=True),
    sa.Column('location_type', sa.String(length=50), nullable=True),
    sa.Column('referral', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('questions', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_applications')
    # ### end Alembic commands ###
