"""Add dashboard_preferences to User

Revision ID: fe9a98885c8d
Revises: 701d539abc7e
Create Date: 2026-02-28 23:32:11.497918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe9a98885c8d'
down_revision = '701d539abc7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dashboard_preferences', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('dashboard_preferences')

    # ### end Alembic commands ###
